"""
Email notification module using Resend.com service
"""
import os
import resend
from typing import Optional
from datetime import datetime
from ..logger import setup_logger


logger = setup_logger(__name__)


class EmailNotifier:
    """Send email notifications with AI news digest using Resend.com"""

    def __init__(
        self,
        resend_api_key: Optional[str] = None,
        email_from: Optional[str] = None,
        email_to: Optional[str] = None
    ):
        """
        Initialize EmailNotifier with Resend.com.

        Args:
            resend_api_key: Resend API key
            email_from: Sender email address (must be verified in Resend)
            email_to: Recipient email address

        All parameters default to environment variables if not provided.
        """
        self.resend_api_key = resend_api_key or os.getenv("RESEND_API_KEY")
        self.email_from = email_from or os.getenv("EMAIL_FROM")
        self.email_to = email_to or os.getenv("EMAIL_TO")

        # Set the Resend API key
        if self.resend_api_key:
            resend.api_key = self.resend_api_key
        else:
            logger.warning("Resend API key not configured")

        # Validate required fields
        if not all([self.resend_api_key, self.email_from, self.email_to]):
            logger.warning(
                "Email notifier not fully configured. "
                "Required: RESEND_API_KEY, EMAIL_FROM, EMAIL_TO"
            )

        logger.info(f"EmailNotifier initialized with Resend.com (from: {self.email_from})")

    def send(self, content: str, subject: Optional[str] = None) -> bool:
        """
        Send email notification with news digest using Resend.

        Args:
            content: Email body content (news digest)
            subject: Email subject. If None, uses default with current date

        Returns:
            True if email sent successfully, False otherwise
        """
        if not all([self.resend_api_key, self.email_from, self.email_to]):
            logger.error("Email notifier is not fully configured. Skipping email send.")
            return False

        try:
            # Create default subject if not provided
            if subject is None:
                today = datetime.now().strftime("%Y-%m-%d")
                subject = f"AI News Digest - {today}"

            # Create HTML email content
            html_content = self._create_html_email(content, subject)

            logger.info(f"Sending email via Resend to {self.email_to}")

            # Send email using Resend
            params = {
                "from": self.email_from,
                "to": [self.email_to],
                "subject": subject,
                "html": html_content,
                "text": content,  # Plain text fallback
            }

            response = resend.Emails.send(params)

            logger.info(f"Email sent successfully via Resend (ID: {response.get('id', 'N/A')})")
            return True

        except Exception as e:
            logger.error(f"Failed to send email via Resend: {str(e)}", exc_info=True)
            return False

    def _create_html_email(self, content: str, subject: str) -> str:
        """
        Create HTML version of email.

        Args:
            content: Plain text content
            subject: Email subject

        Returns:
            HTML formatted email
        """
        # Convert plain text to HTML (basic formatting)
        html_content = content.replace("\n", "<br>")

        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <style>
                body {{
                    font-family: Arial, sans-serif;
                    line-height: 1.6;
                    color: #333;
                    max-width: 800px;
                    margin: 0 auto;
                    padding: 20px;
                }}
                h1 {{
                    color: #2c3e50;
                    border-bottom: 3px solid #3498db;
                    padding-bottom: 10px;
                }}
                .content {{
                    background-color: #f9f9f9;
                    padding: 20px;
                    border-radius: 5px;
                    margin-top: 20px;
                }}
                .footer {{
                    margin-top: 30px;
                    padding-top: 20px;
                    border-top: 1px solid #ddd;
                    font-size: 12px;
                    color: #666;
                }}
            </style>
        </head>
        <body>
            <h1>{subject}</h1>
            <div class="content">
                {html_content}
            </div>
            <div class="footer">
                <p>This email was automatically generated by AI News Bot</p>
                <p>Powered by Anthropic Claude</p>
            </div>
        </body>
        </html>
        """
        return html
